export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const RESEND_ACTIVATION_SUCCESS = "RESEND_ACTIVATION_SUCCESS";
export const RESEND_ACTIVATION_FAIL = "RESEND_ACTIVATION_FAIL";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const Entrust_VALIDATION_SUCCESS = "Entrust_VALIDATION_SUCCESS";
export const Entrust_VALIDATION_FAIL = "Entrust_VALIDATION_FAIL";
export const Entrust_TOKEN_ACTIVATION_START_SUCCESS =
   "Entrust_TOKEN_ACTIVATION_START_SUCCESS";
export const Entrust_TOKEN_ACTIVATION_START_FAIL =
   "Entrust_TOKEN_ACTIVATION_START_FAIL";
export const Entrust_TOKEN_ACTIVATION_COMPLETE_SUCCESS =
   "Entrust_TOKEN_ACTIVATION_COMPLETE_SUCCESS";
export const Entrust_TOKEN_ACTIVATION_COMPLETE_FAIL =
   "Entrust_TOKEN_ACTIVATION_COMPLETE_FAIL";
export const USER_2FA_REGISTRATION_SUCCESS = "USER_2FA_REGISTRATION_SUCCESS";
export const USER_2FA_REGISTRATION_FAIL = "USER_2FA_REGISTRATION_FAIL";
